version: "3.9"
services:
  nginx:
    restart: always
    image: nginx:latest
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:3051"
    depends_on:
      - api
      - frontend

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://api:5000
    ports:
      - "3000:3000"
    command: ["npm", "start"]
